[pytest]
python_files = test_*.py


pythonpath =
    ravr/method
    ravr/allocation
    ravr/codecs
    ravr/common
    tools/codecs
    tools/data_prep/deep1m
    experiments/table1_sop
    experiments/fig2_random_allocations
    experiments/table2_corpora/shared
    experiments/table2_corpora/gldv2_100k
    experiments/table2_corpora/gldv2_762k
    experiments/table2_corpora/deep1m
    experiments/fig3_native_loss

testpaths =
    ravr/tests
    experiments/table1_sop
    experiments/fig3_native_loss
